/*
 * Wallaby.js - v1.0.613
 * http://wallabyjs.com
 * Copyright (c) 2014-2018 Wallaby.js - All Rights Reserved.
 *
 * This source code file is a part of Wallaby.js and is a proprietary (closed source) software.

 * IMPORTANT:
 * Wallaby.js is a tool made by software developers for software developers with passion and love for what we do.
 * Pirating the tool is not only illegal and just morally wrong,
 * it is also unfair to other fellow programmers who are using it legally,
 * and very harmful for the tool and its future.
 */
function NyanCat(e){Base.call(this,e);var t=this,n=(this.stats,.75*Base.window.width|0),i=(this.rainbowColors=t.generateColors(),this.colorIndex=0,this.numberOfLines=4,this.trajectories=[[],[],[],[]],this.nyanCatWidth=11);this.trajectoryWidthMax=n-i,this.scoreboardWidth=5,this.tick=0;e.on("start",function(){Base.cursor.hide(),t.draw()}),e.on("pending",function(e){t.draw()}),e.on("pass",function(e){t.draw()}),e.on("fail",function(e,n){t.draw()}),e.on("end",function(){Base.cursor.show();for(var e=0;e<t.numberOfLines;e++)write("\n");t.epilogue()})}function write(e){process.stdout.write(e)}var Base=require("./base");exports=module.exports=NyanCat,NyanCat.prototype.draw=function(){this.appendRainbow(),this.drawScoreboard(),this.drawRainbow(),this.drawNyanCat(),this.tick=!this.tick},NyanCat.prototype.drawScoreboard=function(){function e(e,t){write(" "),write(Base.color(e,t)),write("\n")}var t=this.stats;e("green",t.passes),e("fail",t.failures),e("pending",t.pending),write("\n"),this.cursorUp(this.numberOfLines)},NyanCat.prototype.appendRainbow=function(){for(var e=this.tick?"_":"-",t=this.rainbowify(e),n=0;n<this.numberOfLines;n++){var i=this.trajectories[n];i.length>=this.trajectoryWidthMax&&i.shift(),i.push(t)}},NyanCat.prototype.drawRainbow=function(){var e=this;this.trajectories.forEach(function(t,n){write("["+e.scoreboardWidth+"C"),write(t.join("")),write("\n")}),this.cursorUp(this.numberOfLines)},NyanCat.prototype.drawNyanCat=function(){var e=this,t=this.scoreboardWidth+this.trajectories[0].length,n="["+t+"C",i="";write(n),write("_,------,"),write("\n"),write(n),i=e.tick?"  ":"   ",write("_|"+i+"/\\_/\\ "),write("\n"),write(n),i=e.tick?"_":"__";var r=e.tick?"~":"^";write(r+"|"+i+this.face()+" "),write("\n"),write(n),i=e.tick?" ":"  ",write(i+'""  "" '),write("\n"),this.cursorUp(this.numberOfLines)},NyanCat.prototype.face=function(){var e=this.stats;return e.failures?"( x .x)":e.pending?"( o .o)":e.passes?"( ^ .^)":"( - .-)"},NyanCat.prototype.cursorUp=function(e){write("["+e+"A")},NyanCat.prototype.cursorDown=function(e){write("["+e+"B")},NyanCat.prototype.generateColors=function(){for(var e=[],t=0;42>t;t++){var n=Math.floor(Math.PI/3),i=t*(1/6),r=Math.floor(3*Math.sin(i)+3),s=Math.floor(3*Math.sin(i+2*n)+3),o=Math.floor(3*Math.sin(i+4*n)+3);e.push(36*r+6*s+o+16)}return e},NyanCat.prototype.rainbowify=function(e){if(!Base.useColors)return e;var t=this.rainbowColors[this.colorIndex%this.rainbowColors.length];return this.colorIndex+=1,"[38;5;"+t+"m"+e+"[0m"},NyanCat.prototype.__proto__=Base.prototype;