/*
 * Wallaby.js - v1.0.544
 * http://wallabyjs.com
 * Copyright (c) 2014-2018 Wallaby.js - All Rights Reserved.
 *
 * This source code file is a part of Wallaby.js and is a proprietary (closed source) software.

 * IMPORTANT:
 * Wallaby.js is a tool made by software developers for software developers with passion and love for what we do.
 * Pirating the tool is not only illegal and just morally wrong,
 * it is also unfair to other fellow programmers who are using it legally,
 * and very harmful for the tool and its future.
 */
var Mocha;if(global.wallaby._testFrameworkPath)Mocha=require(global.wallaby._testFrameworkPath);else try{Mocha=require("mocha")}catch(e){Mocha=require("./framework/index.js")}var mocha,tracer=global.$_$tracer;tracer.start(function(){var e,t=tracer.initialSpecId(),n=[],i=global.$_$session,r=function(){return i!==global.$_$session};mocha.reporter(function(i){var s=i._grep||/.*/,o=i._invert,a=!1;if(i._invert=!1,i.runTest=function(e){if(!r()){var t=this.test,n=this;this.asyncOnly&&(t.asyncOnly=!0);try{t.on("error",function(e){n.fail(t,e)}),tracer.specSyncStart();try{t.run(e)}finally{tracer.specSyncEnd()}}catch(i){e(i)}}},i.grep=function(e,t){s=e,o=t,i._invert=!1},i.grepTotal=function(e){var t=0;return e.eachTest(function(e){var n=s.test(e.fullTitle());o&&(n=!n),n&&t++}),t},i._grep={test:function(e){var t=s.test(e);if(o&&(t=!t),!t)return!1;if(!tracer.hasSpecFilter())return!0;var i=n.slice(1);return i.push(e.substr(i.join(" ").length+(a&&0===i.length?0:1))),tracer.specFilter(i)}},tracer.needToNotifySingleTestRun()){var l=i.hook;i.hook=function(e,t){if(!r()){if("afterEach"!==e)return Function.prototype.apply.call(l,this,arguments);var n=arguments,s=this;tracer.notifySingleTestAfterEach(function(){Function.prototype.apply.call(l,s,n)}),i.hook=l}}}i.on("start",function(){r()||tracer.started({total:i.total})}),i.on("end",function(){r()||tracer.complete()}),i.on("suite",function(t){a=a||!!t.titlePath,r()||(n.push(t.title),e=t)}),i.on("suite end",function(){r()||n.pop()}),i.on("test",function(e){r()||(e._id=++t,e._failures=[],e._time=(new tracer._Date).getTime(),tracer.specStart(e._id,e.title))}),i.on("fail",function(e,t){r()||("hook"===e.type||e._finished?(e._hook="hook"===e.type&&e.title||!0,e._failures=[t],i.emit("test end",e)):e._failures.push(t))}),i.on("test end",function(e){if(!r()){e._finished=!0;var t=tracer.specEnd(),i=e.pending===!0,s={id:e._id,timeRange:t,name:e.title,suite:n.slice(1),success:"passed"===e.state,skipped:i,time:i?0:(new tracer._Date).getTime()-e._time,log:[],hook:e._hook,slow:e.slow?e.duration>e.slow():void 0,testFile:e._testFile};if(!s.success&&!s.skipped)for(var o=e._failures,a=0;a<o.length;a++){var l=o[a];s.log.push(tracer.setAssertionData(l,{message:l.message,stack:l.stack}))}s.log.length||delete s.log,tracer.result(s)}})}),mocha.suite.on("pre-require",function(e){var t=e.it;e.it=function(){var e=Function.prototype.apply.call(t,this,arguments);return e._testFile=tracer.entryFile(),e},e.it.only=t.only,e.it.skip=t.skip}),mocha.run(function(){})}),module.exports={init:function(e){mocha=new Mocha,mocha.files=e;try{mocha.slow&&mocha.slow(global.wallaby.slowTestThreshold),mocha.fullTrace&&mocha.fullTrace()}catch(t){}return mocha}};