<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>wallaby.output</string>
        <key>name</key>
        <string>wallaby-output</string>
        <key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>deletion</string>
			<key>match</key>
			<string>‍{1}[^‍]+‍{1}</string>
			<key>name</key>
			<string>markup.deleted markup.underline</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>insertion</string>
			<key>match</key>
			<string>⁠{1}[^⁠]+⁠{1}</string>
			<key>name</key>
			<string>markup.inserted markup.underline</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>message</string>
			<key>match</key>
			<string>​{5}[^​]+​{5}</string>
			<key>name</key>
			<string>constant.numeric.js</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>suite</string>
			<key>match</key>
			<string>​{4}[^​]+​{4}</string>
			<key>name</key>
			<string>string.value</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>duration</string>
			<key>match</key>
			<string>​{3}[^​]+​{3}</string>
			<key>name</key>
			<string>meta.selector</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>errors</string>
			<key>match</key>
			<string>​{2}[^​]+​{2}</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>link</string>
			<key>match</key>
			<string>​{1}[^​]+​{1}</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
	</array>
    </dict>
</plist>
