/*
 * Wallaby.js - v1.0.529
 * http://wallabyjs.com
 * Copyright (c) 2014-2017 Wallaby.js - All Rights Reserved.
 *
 * This source code file is a part of Wallaby.js and is a proprietary (closed source) software.

 * IMPORTANT:
 * Wallaby.js is a tool made by software developers for software developers with passion and love for what we do.
 * Pirating the tool is not only illegal and just morally wrong,
 * it is also unfair to other fellow programmers who are using it legally,
 * and very harmful for the tool and its future.
 */
var tracer=global.$_$tracer;jasmine.ExceptionFormatter=function(){this.message=function(e){return e?e.name&&e.message?e.name+": "+e.message:e.toString():"empty error"},this.stack=function(e){return e?e.stack:null}},jasmine.SpyStrategy=function(e){e=e||{};var t=e.name||"unknown",n=e.fn||function(){},i=e.getSpy||function(){},r=function(){};this.identity=function(){return t},this.exec=function(){return r.apply(this,arguments)},this.callThrough=function(){return r=n,i()},this.returnValue=function(e){return r=function(){return e},i()},this.returnValues=function(){var e=Array.prototype.slice.call(arguments);return r=function(){return e.shift()},i()},this.throwError=function(e){return r=function(){throw e instanceof Error?e:new Error(e)},i()},this.callFake=function(e){return r=e,i()},this.stub=function(e){return r=function(){},i()}};var jasmineEnv=jasmine.getEnv(),currentSuite=[],originalDescribe=jasmineEnv.describe;jasmineEnv.describe=function(){currentSuite.push(arguments[0]);var e=Function.prototype.apply.call(originalDescribe,this,arguments);return currentSuite.pop(),e};var originalFDescribe=jasmineEnv.fdescribe;jasmineEnv.fdescribe=function(){currentSuite.push(arguments[0]);var e=Function.prototype.apply.call(originalFDescribe,this,arguments);return currentSuite.pop(),e};var existingSpecFilter=jasmineEnv.specFilter.bind(jasmineEnv),originalIt=jasmineEnv.it;jasmineEnv.it=function(){var e=arguments[1];{if("encountered a declaration exception"!==arguments[0]){if(!e)return Function.prototype.apply.call(originalIt,this,arguments);e.length?arguments[1]=function(t){tracer.specSyncStart();try{var n=Function.prototype.apply.call(e,this,arguments)}finally{tracer.specSyncEnd()}return n}:arguments[1]=function(){tracer.specSyncStart();try{var t=Function.prototype.apply.call(e,this,arguments)}finally{tracer.specSyncEnd()}return t};var t=Function.prototype.apply.call(originalIt,this,arguments),n=currentSuite.slice();return n.push(t.description),t.disabled=tracer.hasSpecFilter()&&!tracer.specFilter(n)&&existingSpecFilter(t.description),t}try{e()}catch(i){tracer.reportDeclarationError(i)}}};var originalAfterEach=jasmineEnv.afterEach;jasmineEnv.afterEach=function(){if(tracer.needToNotifySingleTestRun()){var e=arguments[0];e.length?arguments[0]=function(t){tracer.notifySingleTestAfterEach(function(){e(t)})}:arguments[0]=function(t){tracer.notifySingleTestAfterEach(function(){try{e()}finally{t()}})}}return Function.prototype.apply.call(originalAfterEach,this,arguments)},jasmineEnv.addReporter(tracer._jasmineAdapter),jasmineEnv.specFilter=function(){return!0};